{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

# TODO review meta.yml spec and fill in missing fields as necessary (e.g. build number).
package:
  name: q2templates
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - setuptools
    - jinja2
    - pandas {{ pandas }}

test:
  commands:
    - py.test --pyargs q2templates
    
  requires:
    - pytest

  imports:
    - q2templates

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
